python -m unittest -v func_test.TestFunctions.test_front_stocksQuery_valid # 1
python -m unittest -v func_test.TestFunctions.test_front_stocksQuery_invalid # 2
python -m unittest -v func_test.TestFunctions.test_catalog_query_valid # 3
python -m unittest -v func_test.TestFunctions.test_catalog_query_invalid # 4
python -m unittest -v func_test.TestFunctions.test_order_buy_valid # 5
python -m unittest -v func_test.TestFunctions.test_order_sell_valid # 6
python -m unittest -v func_test.TestFunctions.test_order_trade_invalid # 7
python -m unittest -v func_test.TestFunctions.test_order_trade_Buy_outofstock # 8
python -m unittest -v func_test.TestFunctions.test_order_trade_Sell_outofstock # 9
python -m unittest -v func_test.TestFunctions.test_front_buy_valid # 10
python -m unittest -v func_test.TestFunctions.test_front_sell_valid # 11
python -m unittest -v func_test.TestFunctions.test_front_trade_invalid # 12
python -m unittest -v func_test.TestFunctions.test_front_buy_outofstock # 13
python -m unittest -v func_test.TestFunctions.test_front_sell_outofstock # 14
python -m unittest -v func_test.TestFunctions.test_catalog_buy_valid # 15
python -m unittest -v func_test.TestFunctions.test_catalog_sell_valid # 16
python -m unittest -v func_test.TestFunctions.test_catalog_trade_invalid # 17
python -m unittest -v func_test.TestFunctions.test_catalog_buy_outofstock # 18
python -m unittest -v func_test.TestFunctions.test_catalog_sell_outofstock # 19
python -m unittest -v func_test.TestFunctions.test_front_queryOrder_valid # 20
python -m unittest -v func_test.TestFunctions.test_front_queryOrder_invalid # 21
python -m unittest -v func_test.TestFunctions.test_order_queryOrder_valid # 22
python -m unittest -v func_test.TestFunctions.test_order_queryOrder_invalid # 23
python -m unittest -v func_test.TestFunctions.test_ping_valid # 24
python -m unittest -v func_test.TestFunctions.test_leader_valid # 25
